[package]
name = "oxide-auth-warp"
version = "0.1.0"
authors = ["Evin Owen <github@evinowen.net>","David Maul <>","Greg Lamb <email@greglamb.me>"]
repository = "https://github.com/socketworld/oxide-auth-warp.git"
edition = "2018"

[dependencies]
warp = "0.2.5"
oxide-auth = "0.5.0"
